### ISSUE TITLE
Simulation failed because number of scenarios=0

### ISSUE THREAD

**Issue by CrisCloseTheDoor** [motional/nuplan-devkit#122]
### Describe the bug
Simulation failed because number of scenarios=0

### Steps To Reproduce
```
run_simulation.py \
+simulation=open_loop_boxes \
experiment_name='simulation_raster_experiment' \
scenario_builder=nuplan_mini \
scenario_filter=all_scenarios \
scenario_filter.num_scenarios_per_type=10 \
planner=ml_planner \
model=raster_model \
worker=ray_distributed \
planner.ml_planner.model_config=${model} \
planner.ml_planner.checkpoint_path=/***/nuplan/exp/exp/raster_experiment/adamw_steplr/epoch_99.ckpt
```

### Stack Trace
```
Traceback (most recent call last):
(wrapped_fn pid=12111)   File "/***/nuplan/planning/simulation/runner/executor.py", line 23, in run_simulation
(wrapped_fn pid=12111)     return sim_runner.run()  
(wrapped_fn pid=12111)   File "/***/nuplan/planning/simulation/runner/simulations_runner.py", line 160, in run
(wrapped_fn pid=12111)     for_each(lambda sim: sim.callback.on_simulation_end(sim.setup, self.planner, sim.history), self.simulations)
(wrapped_fn pid=12111)   File "/***/nuplan/planning/simulation/runner/simulations_runner.py", line 23, in for_each
(wrapped_fn pid=12111)     fn(item)
(wrapped_fn pid=12111)   File "/***/nuplan/planning/simulation/runner/simulations_runner.py", line 160, in <lambda>
(wrapped_fn pid=12111)     for_each(lambda sim: sim.callback.on_simulation_end(sim.setup, self.planner, sim.history), self.simulations)
(wrapped_fn pid=12111)   File "/***/nuplan/planning/simulation/callback/multi_callback.py", line 60, in on_simulation_end
(wrapped_fn pid=12111)     callback.on_simulation_end(setup, planner, history)
(wrapped_fn pid=12111)   File "/***/nuplan/planning/simulation/callback/simulation_log_callback.py", line 67, in on_simulation_end
(wrapped_fn pid=12111)     raise RuntimeError("Number of scenes has to be greater than 0")
(wrapped_fn pid=12111) RuntimeError: Number of scenes has to be greater than 0
(wrapped_fn pid=12111) WARNING:nuplan.planning.simulation.runner.executor:Simulation failed with error:
(wrapped_fn pid=12111)  Number of scenes has to be greater than 0
(wrapped_fn pid=12111) WARNING:nuplan.planning.simulation.runner.executor:
(wrapped_fn pid=12111) Failed simulation [log,token]:
(wrapped_fn pid=12111)  [2021.07.24.23.50.16_veh-17_01696_02071, fee8a4db35df59e2]
(wrapped_fn pid=12111) 
(wrapped_fn pid=12111) WARNING:nuplan.planning.simulation.runner.executor:----------- Simulation failed!
```

**Comment by JingyuQian** [comment]
Hello, looks like this problem happens in one of the ray workers. Is this reproducible if you change the number of workers in the `ray_distributed.yaml`?
