### ISSUE TITLE
Simulation with GPU doesn't work

### ISSUE THREAD

**Issue by mh0797** [motional/nuplan-devkit#140]
### Describe the bug
If `number_of_gpus_per_simulation `is set to a value other than `null` or another worker than ray_distributed is used, the simulation crashes, because only the model, not the features are moved to gpu. Therefore most torch operations will result in an error `expected all tensors to be on the same device [...]`
### Setup
nuplan-devkit0.6
### Steps To Reproduce
1. Run simulation with number_of_gpus_per_simulation=1 

### Stack Trace
```
(wrapped_fn pid=2806435) WARNING:nuplan.planning.simulation.runner.executor:----------- Simulation failed: with the following trace:
(wrapped_fn pid=2806435) Traceback (most recent call last):
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/simulation/runner/executor.py", line 27, in run_simulation
(wrapped_fn pid=2806435)     return sim_runner.run()  # type: ignore
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/simulation/runner/simulations_runner.py", line 134, in run
(wrapped_fn pid=2806435)     trajectories = self.planner.compute_trajectory(planner_inputs)
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/simulation/planner/abstract_planner.py", line 124, in compute_trajectory
(wrapped_fn pid=2806435)     raise e
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/simulation/planner/abstract_planner.py", line 121, in compute_trajectory
(wrapped_fn pid=2806435)     trajectory = self.compute_planner_trajectory(current_input)
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/simulation/planner/ml_planner/ml_planner.py", line 92, in compute_planner_trajectory
(wrapped_fn pid=2806435)     predictions = self._infer_model(features)
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/simulation/planner/ml_planner/ml_planner.py", line 55, in _infer_model
(wrapped_fn pid=2806435)     predictions = self._model_loader.infer(features)
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/simulation/planner/ml_planner/model_loader.py", line 74, in infer
(wrapped_fn pid=2806435)     return self._model.forward(features)
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/training/modeling/models/model.py", line 132, in forward
(wrapped_fn pid=2806435)     encodings = self.encoder(features)
(wrapped_fn pid=2806435)   File "/home/aah1si/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
(wrapped_fn pid=2806435)     return forward_call(*input, **kwargs)
(wrapped_fn pid=2806435)   File "/home/aah1si/nuplan/nuplan-devkit/nuplan/planning/training/modeling/models/encoder.py", line 118, in forward
(wrapped_fn pid=2806435)     lane_node_embedding = self.leaky_relu(self.node_emb(lane_node_feats))
(wrapped_fn pid=2806435)   File "/home/aah1si/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
(wrapped_fn pid=2806435)     return forward_call(*input, **kwargs)
(wrapped_fn pid=2806435)   File "/home/aah1si/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 96, in forward
(wrapped_fn pid=2806435)     return F.linear(input, self.weight, self.bias)
(wrapped_fn pid=2806435)   File "/home/aah1si/anaconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/functional.py", line 1847, in linear
(wrapped_fn pid=2806435)     return torch._C._nn.linear(input, weight, bias)
(wrapped_fn pid=2806435) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat2 in method wrapper_mm)
(wrapped_fn pid=2806435) WARNING:nuplan.planning.simulation.runner.executor:Simulation failed with error:
(wrapped_fn pid=2806435)  Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat2 in method wrapper_mm)
(wrapped_fn pid=2806435) WARNING:nuplan.planning.simulation.runner.executor:
(wrapped_fn pid=2806435) Failed simulation [log,token]:
(wrapped_fn pid=2806435)  [2021.05.25.14.16.10_veh-35_01690_02183, 4d05197daa3f5a3d]
(wrapped_fn pid=2806435)
(wrapped_fn pid=2806435) WARNING:nuplan.planning.simulation.runner.executor:----------- Simulation failed!
```

**Comment by mh0797** [comment]
Closing since the issue is solved in devkit-1.0
