### ISSUE TITLE
zmq.error.ZMQError: Address already in use

### ISSUE THREAD

**Issue by hunterkeith2017** [motional/nuplan-devkit#165]
script: "nuplan_framework.ipynb"
When I start to train the model in the jupyter notework，something about zmq gets wrong  errors. Does anybody help me?

#####error detail#######
/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/debugpy/adapter/../../debugpy/_vendored/force_pydevd.py:18: UserWarning: incompatible copy of pydevd already imported:
 /root/anaconda3/envs/nuplan/lib/python3.9/site-packages/pydevd_plugins/extensions/pydevd_plugin_omegaconf.py
  warnings.warn(msg + ':\n {}'.format('\n  '.join(_unvendored)))
/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/traitlets/traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '324b6a1c-f8b2-4c86-a018-bb4f5c33026a' instead of 'b"324b6a1c-f8b2-4c86-a018-bb4f5c33026a"'.
  warn(
Traceback (most recent call last):
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3433, in <module>
    main()
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3426, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2502, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2509, in _exec
    globals = pydevd_runpy.run_path(file, globals, '__main__')
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
   _run_code(code, mod_globals, init_globals,
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/traitlets/config/application.py", line 977, in launch_instance
    app.initialize(argv)
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/traitlets/config/application.py", line 110, in inner
    return method(app, *args, **kwargs)
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 666, in initialize
    self.init_sockets()
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 307, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 244, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 220, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "/root/anaconda3/envs/nuplan/lib/python3.9/site-packages/zmq/sugar/socket.py", line 232, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 568, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
Global seed set to 0
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/4
#####################################

**Comment by patk-motional** [comment]
Hi @hunterkeith2017,

It seems that this happens before the training segment of the tutorial. Unfortunately, I am unable to recreate your error. Do you have your virtual environment setup correctly?

**Comment by IvanChen777** [comment]
Hi, @patk-motional , 
I also meet the same issue in v1.0. It seems that I cannot run the trainining code in jupyter notebook, but I can run the training code in terminal, I think the environment setting is fine. Otherwise, it will not work in terminal.

**Comment by gianmarco-motional** [comment]
Have you tried specifying a different port for jupyter?

**Comment by IvanChen777** [comment]
> Have you tried specifying a different port for jupyter?

I don't know what is that mean for specifying a different port for jupyter, I think the problem for my device is that I could only run it in terminal or go to use the remote machine directly to run the jupyter notebook rather than use the remote machine remotely. This situation is also similar when I run the visualization part.

**Comment by rdesc** [comment]
I seem to also be getting this issue when running the notebook  `tutorials/nuplan_framework.ipynb`..
