### ISSUE TITLE
Error: sqlite3.OperationalError: near "(": syntax error

### ISSUE THREAD

**Issue by perone** [motional/nuplan-devkit#167]
### Describe the bug
A SQL error is triggered when running code according the tutorial.

### Setup
```
pip install -r requirements.txt
pip install -r requirements_torch.txt
pip install -e .

HYDRA_FULL_ERROR=1 python nuplan/planning/script/run_training.py     experiment_name=raster_experiment     py_func=train     +training=training_raster_model     scenario_builder=nuplan_mini     scenario_filter.limit_total_scenarios=500     lightning.trainer.params.max_epochs=10     data_loader.params.batch_size=8     data_loader.params.num_workers=8
```

### Stack Trace
```
Traceback (most recent call last):
  File "/home/ubuntu/code/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 117, in ray_map
    results = _ray_map_items(task, *item_lists, log_dir=log_dir)
  File "/home/ubuntu/code/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 100, in _ray_map_items
    for object_id, output in tqdm(_ray_object_iterator(object_ids), total=len(object_ids), desc='Ray objects'):
  File "/home/ubuntu/.pyenv/versions/nuplan/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/ubuntu/code/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 28, in _ray_object_iterator
    yield next_id, ray.get(next_id)
  File "/home/ubuntu/.pyenv/versions/nuplan/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/.pyenv/versions/nuplan/lib/python3.9/site-packages/ray/_private/worker.py", line 2275, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(OperationalError): ray::wrapped_fn() (pid=31292, ip=[hidden])
  File "/home/ubuntu/code/nuplan-devkit/nuplan/planning/utils/multithreading/ray_execution.py", line 59, in wrapped_fn
    result = fn(*args, **kwargs)
  File "/home/ubuntu/code/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario_filter_utils.py", line 438, in get_scenarios_from_log_file
    this_dict = get_scenarios_from_db_file(parameter)
  File "/home/ubuntu/code/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario_filter_utils.py", line 166, in get_scenarios_from_db_file
    for row in get_scenarios_from_db(
  File "/home/ubuntu/code/nuplan-devkit/nuplan/database/nuplan_db/nuplan_scenario_queries.py", line 851, in get_scenarios_from_db
    for row in execute_many(query, args, log_file):
  File "/home/ubuntu/code/nuplan-devkit/nuplan/database/nuplan_db/query_session.py", line 21, in execute_many
    cursor.execute(query_text, query_parameters)
sqlite3.OperationalError: near "(": syntax error
```

**Comment by patk-motional** [comment]
Hi @perone,

Sorry for the late reply. Have you been able to fix the issue? I am not able to recreate your issue
