### ISSUE TITLE
Cannot load nuBoard :: Internal Server Error

### ISSUE THREAD

**Issue by dmachapu** [motional/nuplan-devkit#210]
Dear Motional nuplan Team,

Firstly congratulations to the work you have done!!! Working with nuplan is very interesting.

I have followed the instructions and set up the devkit. I am trying to run the tutorials. I am having issues at the last part of the tutorials. Nuboard is not getting launched. I am getting 500: Internal Server Error.

I am posting the error message from the log below. I would be very thankful to you, if you can help me fix this issue. Anyone else who came across the same issues, kindly share the solution to resolve it.

Thanks in advance. 

ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/bokeh/server/views/doc_handler.py", line 54, in get
    session = await self.get_session()
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/bokeh/server/views/session_handler.py", line 145, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/bokeh/server/contexts.py", line 242, in create_session_if_needed
    self._application.initialize_document(doc)
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/bokeh/application/application.py", line 192, in initialize_document
    h.modify_document(doc)
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/bokeh/application/handlers/function.py", line 143, in modify_document
    self._func(doc)
  File "/home/divya/nuplan-devkit/nuplan/planning/nuboard/nuboard.py", line 113, in main_page
    overview_tab = OverviewTab(doc=self._doc, experiment_file_data=experiment_file_data)
  File "/home/divya/nuplan-devkit/nuplan/planning/nuboard/tabs/overview_tab.py", line 33, in __init__
    super().__init__(doc=doc, experiment_file_data=experiment_file_data)
  File "/home/divya/nuplan-devkit/nuplan/planning/nuboard/base/base_tab.py", line 55, in __init__
    self.planner_checkbox_group.on_click(self._click_planner_checkbox_group)
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/bokeh/core/has_props.py", line 360, in __getattr__
    self._raise_attribute_error_with_matches(name, properties)
  File "/home/divya/miniconda3/envs/nuplan/lib/python3.9/site-packages/bokeh/core/has_props.py", line 368, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'on_click' to CheckboxGroup, possible attributes are active, align, aspect_ratio, classes, context_menu, css_classes, disabled, flow_mode, height, height_policy, inline, js_event_callbacks, js_property_callbacks, labels, margin, max_height, max_width, min_height, min_width, name, resizable, sizing_mode, styles, stylesheets, subscribed_events, syncable, tags, visible, width or width_policy
ERROR:tornado.access:500 GET / (127.0.0.1) 17.33ms

**Comment by michael-motional** [comment]
Hey @dmachapu, sorry for the inconvenience. This is causes by changes in bokeh; in the next version we'll have a proper fix, but for the time being, in `requirements.txt` you can change

```
bokeh>=2.4.2  # Used in the nuBoard dashboard
```

to
```
bokeh==2.4.2  # Used in the nuBoard dashboard
```

as a workaround when building your nuplan virtual env.

**Comment by michael-motional** [comment]
Closing, this is fixed in the upcoming release
