### ISSUE TITLE
"OSError" creating `NuPlanMapWrapper` object

### ISSUE THREAD

**Issue by ChocolateDave** [motional/nuplan-devkit#235]
### Describe the bug

Returns `OSError` while trying to instantiate the `NuPlanMapWrapper` class object.

### Setup

- Python version: `python 3.9.16`. 
- Miniconda Environment: `Miniconda 3 ver. 22.11.1` virtual environment
- System: Debian Linux with kernel version `5.19.0-32-generic`.

### Steps To Reproduce

```python
from nuplan.database.maps_db.gpkg_mapsdb import GPKGMapsDB
from nuplan.database.maps_db.map_api import NuPlanMapWrapper

_map_db = GPKGMapsDB(
    map_version=NUPLAN_MAP_VERSION,
    map_root=NUPLAN_MAPS_ROOT
)
nuplan_map_db = NuPlanMapWrapper(
    maps_db=_map_db,
    map_name='us-nv-las-vegas-strip'
)
```

### Stack Trace

```
Unexpected exception formatting exception. Falling back to standard exception
Traceback (most recent call last):
  File "rasterio[/_base.pyx](https://file+.vscode-resource.vscode-cdn.net/_base.pyx)", line 308, in rasterio._base.DatasetBase.__init__
  File "rasterio[/_base.pyx](https://file+.vscode-resource.vscode-cdn.net/_base.pyx)", line 219, in rasterio._base.open_dataset
  File "rasterio[/_err.pyx](https://file+.vscode-resource.vscode-cdn.net/_err.pyx)", line 221, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: '[/media/data/nuplan/dataset/maps/us-nv-las-vegas-strip/9.15.1915/map.gpkg](https://file+.vscode-resource.vscode-cdn.net/media/data/nuplan/dataset/maps/us-nv-las-vegas-strip/9.15.1915/map.gpkg)' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/interactiveshell.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/interactiveshell.py)", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "[/tmp/ipykernel_292314/110423679.py](https://file+.vscode-resource.vscode-cdn.net/tmp/ipykernel_292314/110423679.py)", line 9, in <module>
    nuplan_map_db = NuPlanMapWrapper(
  File "[/home/juanwu/Desktop/project/cvpr23-nuplan/nuplan-devkit/nuplan/database/maps_db/map_api.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/Desktop/project/cvpr23-nuplan/nuplan-devkit/nuplan/database/maps_db/map_api.py)", line 32, in __init__
    self.available_raster_layers = self._maps_db.get_raster_layer_names(map_name)
  File "[/home/juanwu/Desktop/project/cvpr23-nuplan/nuplan-devkit/nuplan/database/maps_db/gpkg_mapsdb.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/Desktop/project/cvpr23-nuplan/nuplan-devkit/nuplan/database/maps_db/gpkg_mapsdb.py)", line 330, in get_raster_layer_names
    all_layers_dataset = self._get_map_dataset(location)
  File "[/home/juanwu/Desktop/project/cvpr23-nuplan/nuplan-devkit/nuplan/database/maps_db/gpkg_mapsdb.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/Desktop/project/cvpr23-nuplan/nuplan-devkit/nuplan/database/maps_db/gpkg_mapsdb.py)", line 303, in _get_map_dataset
    return rasterio.open(path_on_disk)
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/rasterio/env.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/rasterio/env.py)", line 451, in wrapper
    return f(*args, **kwds)
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/rasterio/__init__.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/rasterio/__init__.py)", line 304, in open
    dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
  File "rasterio[/_base.pyx](https://file+.vscode-resource.vscode-cdn.net/_base.pyx)", line 310, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: '[/media/data/nuplan/dataset/maps/us-nv-las-vegas-strip/9.15.1915/map.gpkg](https://file+.vscode-resource.vscode-cdn.net/media/data/nuplan/dataset/maps/us-nv-las-vegas-strip/9.15.1915/map.gpkg)' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/interactiveshell.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/interactiveshell.py)", line 2057, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py)", line 1288, in structured_traceback
    return FormattedTB.structured_traceback(
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py)", line 1177, in structured_traceback
    return VerboseTB.structured_traceback(
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py)", line 1049, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py)", line 935, in format_exception_as_a_whole
    self.get_records(etb, number_of_lines_of_context, tb_offset) if etb else []
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/site-packages/IPython/core/ultratb.py)", line 1003, in get_records
    lines, first = inspect.getsourcelines(etb.tb_frame)
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/inspect.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/inspect.py)", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "[/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/inspect.py](https://file+.vscode-resource.vscode-cdn.net/home/juanwu/miniconda3/envs/nuplan/lib/python3.9/inspect.py)", line 835, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

### Additional context

I was able to run other Jupyter notebooks from the `tutorial` folder, and one previous issue can be found at #233.

**Comment by ChocolateDave** [comment]
Just a quick follow-up, can someone from the dev-team help me with this issue? Much appreciated!

**Comment by ChocolateDave** [comment]
For those encountering a similar issue, the proper way to use the map data would be to implement direct SQL queries in `nuplan.database.nuplan_db.nuplan_scenario_queries`. I'm closing this issue as it's been resolved.
