### ISSUE TITLE
Data caching failed due to some KeyErrors

### ISSUE THREAD

**Issue by JingyuQian** [motional/nuplan-devkit#79]
I was playing with the dataset and started caching preprocessed features of the Boston training set. The command was:
```bash
python nuplan/planning/script/run_training.py \
    group=$SAVE_DIR \
    cache.cache_path=$CACHE_DIR \
    experiment_name=$EXPERIMENT \
    py_func=cache \
    +training=training_raster_model \
    scenario_builder=nuplan_boston \
```
where `nuplan_boston.yaml`was adapted from the `nuplan_mini.yaml`. I encountered the following error:
```
2022-07-14 12:13:36,206 ERROR {/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py:95}  Failed to compute features for scenario token 65ec7f345e86527b in log 2021.09.30.18.30.00_veh-28_01175_01702
Error: ('6d59f49fa6055c9b',)
ThreadPoolExecutor:   0%|                                                                                                                                                            | 0/20 [19:48<?, ?it/s]Traceback (most recent call last):
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 86, in compute_features
    all_targets: TargetsType = self._compute_all_features(scenario, self._target_builders)
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 112, in _compute_all_features
    feature = compute_or_load_feature(
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/utils/utils_cache.py", line 49, in compute_or_load_feature
    feature = builder.get_targets(scenario)
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/target_builders/ego_trajectory_target_builder.py", line 37, in get_targets
    trajectory_absolute_states = scenario.get_ego_future_trajectory(
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 266, in get_ego_future_trajectory
    for lidar_pc in self._find_matching_lidar_pcs(iteration, num_samples, time_horizon, True)
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 323, in _find_matching_lidar_pcs
    [self._get_next_lidarpc(self._get_lidar_pc_at_iteration(iteration), idx) for idx in indices]
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 323, in <listcomp>
    [self._get_next_lidarpc(self._get_lidar_pc_at_iteration(iteration), idx) for idx in indices]
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 129, in _get_next_lidarpc
    lidarpc = lidarpc_next(lidarpc)
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 643, in wrapper
    cache[k] = v
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 217, in __setitem__
    cache_setitem(self, key, value)
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 79, in __setitem__
    self.popitem()
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 231, in popitem
    return (key, self.pop(key))
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 116, in pop
    raise KeyError(key)
KeyError: ('6d59f49fa6055c9b',)
2022-07-14 12:19:34,051 ERROR {/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py:95}  Failed to compute features for scenario token d18454960a7a58d5 in log 2021.10.18.14.24.40_veh-28_00038_00420
Error: ('a2af8755464952df',)
ThreadPoolExecutor:   0%|                                                                                                                                                            | 0/20 [25:46<?, ?it/s]Traceback (most recent call last):
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 86, in compute_features
    all_targets: TargetsType = self._compute_all_features(scenario, self._target_builders)
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 112, in _compute_all_features
    feature = compute_or_load_feature(
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/utils/utils_cache.py", line 49, in compute_or_load_feature
    feature = builder.get_targets(scenario)
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/target_builders/ego_trajectory_target_builder.py", line 37, in get_targets
    trajectory_absolute_states = scenario.get_ego_future_trajectory(
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 266, in get_ego_future_trajectory
    for lidar_pc in self._find_matching_lidar_pcs(iteration, num_samples, time_horizon, True)
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 323, in _find_matching_lidar_pcs
    [self._get_next_lidarpc(self._get_lidar_pc_at_iteration(iteration), idx) for idx in indices]
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 323, in <listcomp>
    [self._get_next_lidarpc(self._get_lidar_pc_at_iteration(iteration), idx) for idx in indices]
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 129, in _get_next_lidarpc
    lidarpc = lidarpc_next(lidarpc)
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 643, in wrapper
    cache[k] = v
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 217, in __setitem__
    cache_setitem(self, key, value)
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 79, in __setitem__
    self.popitem()
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 231, in popitem
    return (key, self.pop(key))
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 114, in pop
    del self[key]
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 221, in __delitem__
    cache_delitem(self, key)
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 90, in __delitem__
    del self.__data[key]
KeyError: ('a2af8755464952df',)
2022-07-14 12:20:56,642 ERROR {/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py:95}  Failed to compute features for scenario token 84fc71ccacac539d in log 2021.08.20.13.59.49_veh-28_00956_01631
Error: '378732d3c95b5a44'
ThreadPoolExecutor:   0%|                                                                                                                                                            | 0/20 [27:08<?, ?it/s]Traceback (most recent call last):
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 86, in compute_features
    all_targets: TargetsType = self._compute_all_features(scenario, self._target_builders)
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 112, in _compute_all_features
    feature = compute_or_load_feature(
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/utils/utils_cache.py", line 49, in compute_or_load_feature
    feature = builder.get_targets(scenario)
  File "/home/users/user/nuplan-devkit/nuplan/planning/training/preprocessing/target_builders/ego_trajectory_target_builder.py", line 37, in get_targets
    trajectory_absolute_states = scenario.get_ego_future_trajectory(
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 266, in get_ego_future_trajectory
    for lidar_pc in self._find_matching_lidar_pcs(iteration, num_samples, time_horizon, True)
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 323, in _find_matching_lidar_pcs
    [self._get_next_lidarpc(self._get_lidar_pc_at_iteration(iteration), idx) for idx in indices]
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 323, in <listcomp>
    [self._get_next_lidarpc(self._get_lidar_pc_at_iteration(iteration), idx) for idx in indices]
  File "/home/users/user/nuplan-devkit/nuplan/planning/scenario_builder/nuplan_db/nuplan_scenario.py", line 129, in _get_next_lidarpc
    lidarpc = lidarpc_next(lidarpc)
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 643, in wrapper
    cache[k] = v
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 217, in __setitem__
    cache_setitem(self, key, value)
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 79, in __setitem__
    self.popitem()
  File "/home/users/user/miniconda3/envs/nuplan/lib/python3.9/site-packages/cachetools/__init__.py", line 227, in popitem
    key = next(iter(self.__order))
KeyError: '378732d3c95b5a44'
```
Looks like some sort of KeyError during caching, but I'm not sure what they are. The error message is a bit long so I'm just copy-pasting some of it. 

Also, I think this part in `feature_preprocessor.py`:
```python
except Exception as error:
      msg = (
          f"Failed to compute features for scenario token {scenario.token} in log {scenario.log_name}\n"
          f"Error: {error}"
      )

      logger.error(msg)
      traceback.print_exc()
      raise RuntimeError(msg)
```
though printing useful error messages, isn't very satisfying to read especially when workerpool is multi-threaded. Just a small suggestion.

Edit: Also had this problem in the mini set

**Comment by patk-motional** [comment]
Hi @JingyuQian,

We just updated the master branch. Can you try it with the v0.3 update?

**Comment by JingyuQian** [comment]
It looks like after the v0.3 update, this issue is gone.
