### ISSUE TITLE
Error in nuplan_framework tutorial

### ISSUE THREAD

**Issue by cgenctor** [motional/nuplan-devkit#98]
Hi,
When I run the training in "nuplan_framework" tutorial, I get the following errors:

- fiona._err.CPLE_OpenFailedError: '~/nuplan/dataset/maps/us-nv-las-vegas-strip/9.15.1915/map.gpkg' not recognized as a supported file format.
- RuntimeError: Caught RuntimeError in DataLoader worker process 0.
- RuntimeError: Failed to compute features for scenario token 8473c207cc0955b7 in log 2021.06.14.18.42.45_veh-12_03445_03902
- Error: sqlite3_get_table(pragma table_info('meta')) failed: disk I/O error

Do you maybe know what they are related to? Thanks in advance

**Setup**
type of machine: Lab Computer
linux distribution: NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

Number of CPUs per node: 8
Number of GPUs per node: 1
Number of threads across all nodes: 8
CUDA Version: 11.4
conda env: ~/miniconda3/envs/nuplan
nuplan-devkit release version: v0.3

**Steps to reproduce the behavior:**
    cd ~/nuplan-devkit/tutorials
    Run command jupyter-notebook nuplan_framework.ipynb

**Stack Trace**
`/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:73: UserWarning: num_workers>0, persistent_workers=False, and accelerator=ddp_spawn may result in data loading bottlenecks. Consider setting persistent_workers=True (this is a limitation of Python .spawn() and PyTorch)
  rank_zero_warn(
/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/pytorch_lightning/callbacks/lr_monitor.py:97: RuntimeWarning: You are using `LearningRateMonitor` callback with models that have no learning rate schedulers. Please see documentation for `configure_optimizers` method.
  rank_zero_warn([W pthreadpool-cpp.cc:90] Warning: Leaking Caffe2 thread-pool after fork. (function pthreadpool)
/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)`

and 

`Traceback (most recent call last):
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 85, in compute_features
    all_features: FeaturesType = self._compute_all_features(scenario, self._feature_builders)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 112, in _compute_all_features
    feature = compute_or_load_feature(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/utils/utils_cache.py", line 47, in compute_or_load_feature
    feature = builder.get_features_from_scenario(scenario)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_builders/raster_feature_builder.py", line 95, in get_features_from_scenario
    return self._compute_feature(ego_state, detections, map_api)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_builders/raster_feature_builder.py", line 117, in _compute_feature
    roadmap_raster = get_roadmap_raster(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/features/raster_utils.py", line 208, in get_roadmap_raster
    coords, _ = _get_layer_coords(focus_agent, map_api, SemanticMapLayer[feature_name], 'polygon', radius)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/features/raster_utils.py", line 79, in _get_layer_coords
    nearest_vector_map = map_api.get_proximal_map_objects(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 160, in get_proximal_map_objects
    object_map[layer] = self._get_proximity_map_object(patch, layer)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 321, in _get_proximity_map_object
    return [self.get_map_object(map_object_id, layer) for map_object_id in map_object_ids]
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 321, in <listcomp>
    return [self.get_map_object(map_object_id, layer) for map_object_id in map_object_ids]
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 168, in get_map_object
    map_object: MapObject = self._map_object_getter[layer](object_id)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 333, in _get_lane
    self._get_vector_map_layer(SemanticMapLayer.LANE_CONNECTOR),
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 252, in _get_vector_map_layer
    return self._load_vector_map_layer(layer_id)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 277, in _load_vector_map_layer
    self._vector_map[layer_name] = self._maps_db.load_vector_layer(self._map_name, layer_name).set_index(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/database/maps_db/gpkg_mapsdb.py", line 247, in load_vector_layer
    map_meta = gpd.read_file(path_on_disk, layer="meta")
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/geopandas/io/file.py", line 253, in _read_file
    return _read_file_fiona(
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/geopandas/io/file.py", line 301, in _read_file_fiona
    if features.crs and "init" in features.crs
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/fiona/collection.py", line 215, in crs
    self._crs = self.session.get_crs()
  File "fiona/ogrext.pyx", line 742, in fiona.ogrext.Session.get_crs
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_AppDefinedError: sqlite3_get_table(pragma table_info('meta')) failed: disk I/O error`

also

` Traceback (most recent call last):
  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: '/home/WIN-UNI-DUE/sjcagenc/nuplan/dataset/maps/us-nv-las-vegas-strip/9.15.1915/map.gpkg' not recognized as a supported file format.
`
During handling of the above exception, another exception occurred:
`
Traceback (most recent call last):
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 85, in compute_features
    all_features: FeaturesType = self._compute_all_features(scenario, self._feature_builders)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_preprocessor.py", line 112, in _compute_all_features
    feature = compute_or_load_feature(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/utils/utils_cache.py", line 47, in compute_or_load_feature
    feature = builder.get_features_from_scenario(scenario)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_builders/raster_feature_builder.py", line 95, in get_features_from_scenario
    return self._compute_feature(ego_state, detections, map_api)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/feature_builders/raster_feature_builder.py", line 117, in _compute_feature
    roadmap_raster = get_roadmap_raster(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/features/raster_utils.py", line 208, in get_roadmap_raster
    coords, _ = _get_layer_coords(focus_agent, map_api, SemanticMapLayer[feature_name], 'polygon', radius)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/planning/training/preprocessing/features/raster_utils.py", line 79, in _get_layer_coords
    nearest_vector_map = map_api.get_proximal_map_objects(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 160, in get_proximal_map_objects
    object_map[layer] = self._get_proximity_map_object(patch, layer)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 321, in _get_proximity_map_object
    return [self.get_map_object(map_object_id, layer) for map_object_id in map_object_ids]
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 321, in <listcomp>
    return [self.get_map_object(map_object_id, layer) for map_object_id in map_object_ids]
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 168, in get_map_object
    map_object: MapObject = self._map_object_getter[layer](object_id)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 335, in _get_lane
    self._get_vector_map_layer(SemanticMapLayer.BOUNDARIES),
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 252, in _get_vector_map_layer
    return self._load_vector_map_layer(layer_id)
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/common/maps/nuplan_map/nuplan_map.py", line 277, in _load_vector_map_layer
    self._vector_map[layer_name] = self._maps_db.load_vector_layer(self._map_name, layer_name).set_index(
  File "/home/WIN-UNI-DUE/sjcagenc/nuplan-devkit/nuplan/database/maps_db/gpkg_mapsdb.py", line 247, in load_vector_layer
    map_meta = gpd.read_file(path_on_disk, layer="meta")
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/geopandas/io/file.py", line 253, in _read_file
    return _read_file_fiona(
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/geopandas/io/file.py", line 294, in _read_file_fiona
    with reader(path_or_bytes, **kwargs) as features:
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/fiona/env.py", line 408, in wrapper
    return f(*args, **kwargs)
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/fiona/__init__.py", line 264, in open
    c = Collection(path, mode, driver=driver, encoding=encoding,
  File "/home/WIN-UNI-DUE/sjcagenc/miniconda3/envs/nuplan/lib/python3.9/site-packages/fiona/collection.py", line 162, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 540, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: '/home/WIN-UNI-DUE/sjcagenc/nuplan/dataset/maps/us-nv-las-vegas-strip/9.15.1915/map.gpkg' not recognized as a supported file format.`

**Comment by patk-motional** [comment]
Hi @cgenctor,

We've just updated the devkit to v0.4. Can you re-try with the latest release?

**Comment by gianmarco-motional** [comment]
I'll close the issue for inactivity. If you still are facing the problem with the current devkit version, feel free to reopen it!
